Repository NoroffFEU/agency.noroff.dev, pull requests merged in 2023-10, with the labels that each got.

#294 check if viewListingsButton is defined
  src/js/listeners/auth/isLoggedIn.js
Labels: bug

#362 317 modal
  pages/TBD/apply/index.html
  pages/listings/listing/create/index.html
  pages/listings/listing/edit/index.html
Labels: documentation

#269 Set justify-content-center on listingContainer
  pages/listings/index.html
Labels: To do

#383 Adds bold font weight to h4s in footers
  src/js/ui/footer/index.js
Labels: Ideas

#347 tidy opp head for all pages
  index.html
  pages/TBD/apply/index.html
  pages/TBD/client/application/index.html
  pages/TBD/index.html
  pages/TBD/listings.html
  pages/listings/index.html
  pages/user/index.html
  privacy_policy.html
  terms_of_use.html
Labels: documentation, question

#296 Added usedetails funtion
  pages/auth/register/company/index.html
  pages/user/index.html
  src/js/api/auth/login.js
  src/js/listeners/profile/profileRouter.js
  src/js/listeners/profile/showUserDetails.js
  src/js/templates/profile/userDetailsTemplate.js
  src/js/views/admin/showUsers.js
Labels: bug, enhancement, Sprint planning

#398 BUGFIX coment out incoret imports oss scss file
  src/scss/custom/auth/index.scss
  src/scss/index.scss
Labels: bug

#410 Adds js extension to file import
  package-lock.json
  src/js/listeners/profile/showUserDetails.js
Labels: bug

#412 Corrects the path of the import in the file
  src/js/listeners/profile/showUserDetails.js
Labels: bug

#427 Applies styling to the banner image
  src/scss/custom/_clientApplication.scss
Labels: bug
