Repository NoroffFEU/agency.noroff.dev, pull requests merged in 2024-01, with the labels that each got.

#482 configure Jest and fix broken test setup
  babel.config.json
  jest-env-vars.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/js/api/auth/login.test.js
  src/js/api/auth/logout.test.js
  src/js/api/auth/register.test.js
  src/js/api/offers/createOffer.test.js
  src/js/api/posts/create.js
  src/js/api/posts/create.test.js
  src/js/api/posts/getListOfListings.js
  src/js/api/posts/getListOfListings.test.js
  src/js/views/admin/showApplicants.test.js
Labels: bug

#578 fix broken register function
  src/js/api/auth/register.js
  src/js/listeners/auth/setRegisterFormListenerApplicant.js
Labels: bug

#689 Refactor singleApplicationTemplate to Use Actual API
  src/js/templates/application/student/singleApplicationTemplate.js
Labels: bug, documentation

#714 Fix all unit tests and update eslint testing confic
  .eslintrc.json
  eslint.config.json
  jest.setup.js
  src/js/api/application/deleteApplication.test.js
  src/js/api/auth/callLoginApi.js
  src/js/api/auth/callLoginApi.test.js
  src/js/api/auth/login.js
  src/js/api/auth/login.test.js
  src/js/api/auth/register.test.js
  src/js/api/offer/deleteOffer.test.js
  src/js/api/offers/createOffer.test.js
  src/js/api/posts/create.test.js
  src/js/api/posts/deleteSingleListing.test.js
  src/js/api/posts/editSingleListing.test.js
  src/js/api/posts/getSingleListing.test.js
  src/js/views/admin/showApplicants.test.js
Labels: testing

#726 Fix styling issue in _allListingPage.scss
  src/scss/custom/_allListingPage.scss
Labels: bug

#571 Integrate CI/CD Workflow with GitHub Actions
  .DS_Store
  .github/workflows/CI.yml
  .github/workflows/static.yml
  README.md
  documentation/GitHub-actions-pipeline.md
  src/js/api/auth/login.js
  src/js/api/auth/login.test.js
  src/js/api/auth/logout.test.js
  src/js/api/auth/register-company.js
  src/js/api/auth/utils.js
  src/js/api/decodeFunction.js
  src/js/api/posts/deleteListing.js
  src/js/api/posts/getListOfListings.js
  src/js/listeners/auth/logoutListener.js
  src/js/listeners/auth/showRegFormListener.js
  src/js/listeners/post/index.js
  src/js/listeners/post/postApplication.js
  src/js/listeners/post/searchListing.js
  src/js/templates/listings/optionEvents.js
  src/js/templates/profile/createInput.js
  src/js/views/admin/showApplicants.test.js
  src/js/views/admin/showListings.js
Labels: enhancement, testing

#754 add build step to pipeline
  .github/workflows/CI.yml
  documentation/GitHub-actions-pipeline.md
  index.js
  src/js/templates/listings/options.js
Labels: tests

#755 Update README Documentation
  README.md
Labels: documentation

#803 Tests/setup cypress and initial test journey
  .eslintrc.json
  cypress.config.js
  cypress/cypress.d.ts
  cypress/e2e/1-getting-started/create.cy.js
  cypress/e2e/e2etest.cy.js
  cypress/e2e/home.cy.js
  cypress/e2e/login.cy.js
  cypress/support/commands.js
  cypress/support/testing/e2etest.cy.js
  package-lock.json
  package.json
Labels: testing

#840 fix pipeline concurrency issue
  .github/workflows/CI.yml
Labels: bug

#883 version 2 of WCAG-listingpage
  pages/auth/register/applicant/index.html
  pages/listings/index.html
  src/js/templates/listings/renderListings.js
  src/js/ui/footer/index.js
  src/js/ui/header/header.js
  src/scss/custom/_footer.scss
  src/scss/custom/_themeColorVariables.scss
  src/scss/index.scss
Labels: enhancement

#990 Fix naming convention typos and improve clarity
  documentation/naming-convention.md
Labels: documentation

#998 992 link doc to readme
  README.md
  documentation/E2E-testing-guide.md
  documentation/ca-purpose.md
  documentation/useful-information.md
Labels: documentation

#849 E2E test links in header & deleteUser unit test
  cypress/e2e/active-links.cy.js
  cypress/index.d.ts
  src/js/api/users/deleteUser.test.js
  src/js/ui/header/header.js
Labels: testing

#917 913 update how to branch
  documentation/how-to-branch.md
Labels: documentation

#1025 Further unit tests
  package-lock.json
  package.json
  src/js/api/auth/index.js
  src/js/api/auth/registerCompany.js
  src/js/api/auth/registerCompany.test.js
  src/js/api/posts/getListOfListings.js
  src/js/listeners/post/createListing.js
  src/js/listeners/post/searchListing.js
  src/js/listeners/post/searchListing.test.js
Labels: testing

#1021 add e2e tests to pipeline
  .github/workflows/CI.yml
  cypress.config.js
  cypress/e2e/active-links.cy.js
  cypress/e2e/header-change.cy.js
  cypress/e2e/home.cy.js
  cypress/e2e/login.cy.js
  cypress/index.d.ts
  cypress/support/commands.js
  cypress/support/e2e.js
  documentation/E2E-testing-guide.md
  package-lock.json
  pages/auth/login/index.html
Labels: testing

#1031 Create unit-testing guide
  documentation/unit-testing-guide.md
Labels: documentation
